name: Deploy Astro Blog to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      # 4️⃣ Install dependencies
      - run: pnpm install

      # 5️⃣ Build Astro project
      - run: pnpm build

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: dist
